"""Domain-specific XML request-document builders for the HMC REST API."""

# The package intentionally re-exports the stable pre-release builder surface.
from .access import (
                      build_hmc_user_document,
                      build_logon_request_document,
                      build_remote_access_document,
                      merge_remote_access_document,
)
from .adapters import (
                      build_client_network_adapter_document,
                      build_vfc_adapter_document,
                      build_vscsi_adapter_document,
)
from .boot import (
                      BOOT_DEVICE_SELECTORS,
                      _build_pending_boot_string,
                      build_boot_order_document,
                      build_clear_boot_order_document,
)
from .common import (
                      AUTHENTICATION_TYPES,
                      KEYLOCK_POSITIONS,
                      MEM_MIRRORING_MODES,
                      OS_TYPES,
                      PARTITION_TYPES,
                      POWER_OFF_POLICIES,
                      POWER_ON_LPAR_START_POLICIES,
                      SHARING_MODES,
                      STORAGE_KINDS,
                      AuthenticationType,
                      BootDeviceSelector,
                      Keylock,
                      LparResources,
                      MemoryMirroringMode,
                      OsType,
                      PartitionType,
                      PowerOffPolicy,
                      PowerOnLparStartPolicy,
                      SharingMode,
                      StorageKind,
)
from .lpar import (
                      VIOS_DEFAULT_RESOURCES,
                      build_dlpar_mem_document,
                      build_dlpar_proc_document,
                      build_lpar_document,
                      build_vios_document,
)
from .storage import (
                      build_brokered_file_document,
                      build_linked_optical_media_document,
                      build_media_repository_delete_document,
                      build_virtual_disk_delete_document,
                      build_virtual_disk_document,
                      build_virtual_network_document,
                      build_virtual_optical_mapping_document,
                      build_virtual_optical_media_delete_document,
                      build_volume_group_document,
                      build_vscsi_mapping_document,
)
from .system import build_managed_system_document

__all__ = [
                      "AUTHENTICATION_TYPES",
                      "BOOT_DEVICE_SELECTORS",
                      "KEYLOCK_POSITIONS",
                      "MEM_MIRRORING_MODES",
                      "OS_TYPES",
                      "PARTITION_TYPES",
                      "POWER_OFF_POLICIES",
                      "POWER_ON_LPAR_START_POLICIES",
                      "SHARING_MODES",
                      "STORAGE_KINDS",
                      "VIOS_DEFAULT_RESOURCES",
                      "AuthenticationType",
                      "BootDeviceSelector",
                      "Keylock",
                      "LparResources",
                      "MemoryMirroringMode",
                      "OsType",
                      "PartitionType",
                      "PowerOffPolicy",
                      "PowerOnLparStartPolicy",
                      "SharingMode",
                      "StorageKind",
                      "_build_pending_boot_string",
                      "build_boot_order_document",
                      "build_brokered_file_document",
                      "build_clear_boot_order_document",
                      "build_client_network_adapter_document",
                      "build_dlpar_mem_document",
                      "build_dlpar_proc_document",
                      "build_hmc_user_document",
                      "build_linked_optical_media_document",
                      "build_logon_request_document",
                      "build_lpar_document",
                      "build_managed_system_document",
                      "build_media_repository_delete_document",
                      "build_remote_access_document",
                      "build_vfc_adapter_document",
                      "build_vios_document",
                      "build_virtual_disk_delete_document",
                      "build_virtual_disk_document",
                      "build_virtual_network_document",
                      "build_virtual_optical_mapping_document",
                      "build_virtual_optical_media_delete_document",
                      "build_volume_group_document",
                      "build_vscsi_adapter_document",
                      "build_vscsi_mapping_document",
                      "merge_remote_access_document",
]
