from __future__ import annotations

from ..xmlutil import escapes_string_arguments
from .common import document_envelope


def _adapter_document(
    root_element: str,
    partition_id_field: tuple[str, str],
    slot_field: tuple[str, str],
    vios_partition_id: int,
    vios_slot: int,
    slot_number: int | None = None,
) -> str:
    """Build a virtual client adapter document from the shared skeleton.

    *partition_id_field* / *slot_field* are ``(element, kb)`` pairs for the
    VIOS-side remote fields, which differ per adapter type (vSCSI vs vFC).
    The client VirtualSlotNumber is emitted only when *slot_number* is given;
    the HMC auto-assigns it otherwise.
    """
    (id_name, id_kb), (slot_name, slot_kb) = partition_id_field, slot_field
    slot = ""
    if slot_number is not None:
        slot = f'  <VirtualSlotNumber kb="COD" kxe="false">{slot_number}</VirtualSlotNumber>\n'
    body = f"""  <Metadata><Atom/></Metadata>
  <AdapterType kb="ROR" kxe="false">Client</AdapterType>
{slot}  <{id_name} kb="{id_kb}" kxe="false">{vios_partition_id}</{id_name}>
  <{slot_name} kb="{slot_kb}" kxe="false">{vios_slot}</{slot_name}>"""
    return document_envelope(root_element, body)


@escapes_string_arguments
def build_vscsi_adapter_document(
    vios_partition_id: int,
    vios_slot: int,
    slot_number: int | None = None,
) -> str:
    """Virtual SCSI client adapter, paired to a VIOS server adapter.

    vios_partition_id / vios_slot identify the VIOS and its server-side slot
    that own the backing storage. slot_number is the client adapter's virtual
    slot (auto-assigned by the HMC if omitted).
    """
    return _adapter_document(
        "VirtualSCSIClientAdapter",
        ("RemoteLogicalPartitionID", "CUR"),
        ("RemoteSlotNumber", "CUA"),
        vios_partition_id,
        vios_slot,
        slot_number,
    )


@escapes_string_arguments
def build_vfc_adapter_document(
    vios_partition_id: int,
    vios_slot: int,
    slot_number: int | None = None,
) -> str:
    """Virtual Fibre Channel (NPIV) client adapter, paired to a VIOS.

    ConnectingPartitionID / ConnectingVirtualSlotNumber identify the VIOS and
    its server-side FC slot. The WWPNs are generated by the HMC on creation.
    """
    return _adapter_document(
        "VirtualFibreChannelClientAdapter",
        # No live V10R3 kb value is recorded for these two fields (#961).
        ("ConnectingPartitionID", "CUD"),
        ("ConnectingVirtualSlotNumber", "CUD"),
        vios_partition_id,
        vios_slot,
        slot_number,
    )


@escapes_string_arguments
def build_client_network_adapter_document(
    port_vlan_id: int,
    slot_number: int | None = None,
    virtual_switch_id: int | None = None,
    tagged: bool = False,
    mac_address: str | None = None,
) -> str:
    """Virtual Ethernet client network adapter.

    port_vlan_id is the PVID (the VLAN the adapter sits on). virtual_switch_id
    selects a specific vSwitch (default switch used if omitted). tagged=True
    makes this a tagged (VLAN-trunking) adapter; mac_address pins the MAC
    (otherwise the HMC generates one).
    """
    parts = ["  <Metadata><Atom/></Metadata>"]
    if slot_number is not None:
        parts.append(
            f'  <VirtualSlotNumber kb="COD" kxe="false">{slot_number}</VirtualSlotNumber>'
        )
    if virtual_switch_id is not None:
        parts.append(
            f'  <VirtualSwitchID kb="ROR" kxe="false">{virtual_switch_id}</VirtualSwitchID>'
        )
    parts.append(f'  <PortVLANID kb="CUR" kxe="false">{port_vlan_id}</PortVLANID>')
    if tagged:
        parts.append('  <IsTaggedVLAN kb="CUD" kxe="false">true</IsTaggedVLAN>')
    if mac_address:
        parts.append(f'  <MACAddress kb="CUR" kxe="false">{mac_address}</MACAddress>')
    body = "\n".join(parts)
    return document_envelope("ClientNetworkAdapter", body)


# Virtual storage (children of VirtualIOServer)
#
# Model (from IBM's HmcRestClient reference + the HMC REST spec):
#   VolumeGroup      PUT to VirtualIOServer/{uuid}/VolumeGroup creates;
#                    POST to .../VolumeGroup/{vg_uuid} modifies (add PVs,
#                    create/delete/extend Virtual Disks, media repository).
#   VirtualDisk      a logical volume carved from a VG; created via a POST of
#                    the VolumeGroup document carrying a VirtualDisks block.
#   VirtualSCSIMapping  POST to the VIOS document carrying a
#                    VirtualSCSIMappings block; connects a backing storage
#                    (PhysicalVolume or VirtualDisk) to an LPAR (Atom link).
