#!/usr/bin/env python3
"""Guard: every generated document under ``docs/`` is current, and the arrangement
that produces it is intact. See ADR 0098.

A generated document declares itself on its first line::

    <!-- Generated by <script>; do not edit. Regenerate: just <name>-docs -->

That banner is the whole registration for a Markdown document under ``docs/``. This
guard reads it, so the set of generated documents and the command that rebuilds each
of them are derived from the tree rather than restated in a list somebody has to
remember to edit.

For every distinct regeneration command the guard copies the working tree into a
temporary directory **without** the top-level ``docs/``, runs the command there, and
compares what it produced against what is committed. Executing is the point: a
recipe whose body is ``true`` produces nothing, so every document naming it is
reported. Starting from an empty ``docs/`` is equally deliberate -- copying the
committed pages in first would let a no-op command pass by leaving them alone.

The check runs in both directions:

* a committed document its command did not produce, or produced differently;
* a produced file that is not committed, or is committed differently;
* a produced Markdown file carrying no banner, which would be an unwalked document;
* a banner naming a recipe the justfile does not define;
* a recipe named ``*-docs`` that no banner names -- the deletion catch;
* a banner on a document outside ``docs/``, which nothing here would ever check.

Finding no banner at all fails too. A universal claim over an empty set is true and
worthless, so an emptied walk reddens rather than passing.

Usage:
    python scripts/check_generated_docs.py [--repo-root <path>]

The guard itself needs ``just``. The recipes it runs need whatever they need --
for this repository, ``uv`` and a populated ``.venv``. Exits 0 when every check
passes; exits 1 and names each failure otherwise.
"""

from __future__ import annotations

import argparse
import difflib
import os
import re
import shlex
import shutil
import signal
import subprocess
import sys
import tempfile
from collections import defaultdict
from pathlib import Path

# Resolve the repo root relative to this script so the guard can be run from any
# working directory, exactly as scripts/check_adr_numbering.py does.
_SCRIPT_DIR = Path(__file__).resolve().parent
_REPO_ROOT = _SCRIPT_DIR.parent

# The recipe group carries the `*-docs` suffix on purpose. The guard *executes*
# what the banner names, so the banner must not be able to name `setup`, and the
# suffix is what the orphan clause below already quantifies over.
_BANNER = re.compile(
    r"^<!-- Generated by (?P<generator>\S+); do not edit\. "
    r"Regenerate: just (?P<recipe>[a-z][a-z0-9-]*-docs) -->$"
)
# A first line trying to be a banner and failing. Anchored on the comment opener so
# a page merely *titled* "Reports generated by the nightly export" is prose, not a
# near miss; without the clause entirely, a typo would quietly remove a document
# from the walked set instead of reporting a problem.
_BANNER_HINT = re.compile(r"^<!--.*(?:generated by|do not edit)", re.IGNORECASE)
# ADR 0098 §3: the naming convention that makes the deletion catch possible.
_REGENERATION_RECIPE = re.compile(r"^[a-z][a-z0-9-]*-docs$")

_DOCS = "docs"
# Directories that are never repository content, at any depth.
_PRUNED_ANYWHERE = frozenset({
    ".git",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    "__pycache__",
    "node_modules",
})
# Build output and environments, which exist only at the root. Anchored, so a source
# directory legitimately named `build` is not silently dropped from the scratch tree.
_PRUNED_AT_ROOT = frozenset({".venv", ".wheel-venv", "build", "dist", "htmlcov"})
# Comfortably inside the 20-minute CI job, so a hung generator is reported as a
# timeout naming the command that hung rather than as a cancelled job.
_TIMEOUT_SECONDS = 600
# How many differing files get a full diff before the rest are only named. A change
# to a generator's output format makes every page differ at once, and 35 whole-file
# diffs on each of eight CI legs buries the one line saying what to do about it.
_MAX_DIFFS = 3


class GeneratedDocsError(RuntimeError):
    """The check cannot run, as distinct from finding the tree in a bad state."""


def markdown_files(root: Path) -> list[Path]:
    """Every Markdown file in *root*, skipping environments, caches and build output.

    The whole tree, not just ``docs/``: a banner outside ``docs/`` is a document
    nothing would check, and the walk has to see it to say so.
    """
    found: list[Path] = []
    for directory, subdirectories, names in os.walk(root):
        here = Path(directory)
        subdirectories[:] = sorted(
            name
            for name in subdirectories
            if name not in _PRUNED_ANYWHERE
            and not (here == root and name in _PRUNED_AT_ROOT)
        )
        found.extend(here / name for name in sorted(names) if name.endswith(".md"))
    return found


def read_banners(root: Path) -> tuple[dict[Path, str], list[str]]:
    """Every generated document in *root*, mapped to its regeneration recipe.

    Only the first line is read. A record that quotes the banner format inside its
    prose -- ADR 0098 does -- is not a generated document, and reading further would
    make it one.
    """
    banners: dict[Path, str] = {}
    errors: list[str] = []
    for path in markdown_files(root):
        relative = path.relative_to(root)
        first = _first_line(path)
        match = _BANNER.match(first)
        if match is None:
            if _BANNER_HINT.match(first):
                errors.append(
                    f"{relative}: first line looks like a generation banner but does "
                    f"not match '<!-- Generated by <script>; do not edit. Regenerate: "
                    f"just <name>-docs -->'; a near miss would silently leave the "
                    f"document unchecked"
                )
            continue
        if relative.parts[0] != _DOCS:
            errors.append(
                f"{relative}: carries a generation banner but lives outside "
                f"{_DOCS}/, where this guard does not look. Move it under {_DOCS}/ "
                f"or take the banner off."
            )
            continue
        banners[relative] = match["recipe"]
    return banners, errors


def _first_line(path: Path) -> str:
    text = path.read_text(encoding="utf-8", errors="replace")
    return text.split("\n", 1)[0].strip()


def just_recipes(root: Path) -> set[str]:
    """The justfile's recipe names, from ``just`` rather than from a regex."""
    try:
        result = subprocess.run(  # noqa: S603 - fixed argv, no shell
            ["just", "--summary"],  # noqa: S607 - on PATH, as CI installs it
            cwd=root,
            capture_output=True,
            text=True,
            timeout=_TIMEOUT_SECONDS,
            check=False,
        )
    except OSError as error:  # pragma: no cover - `just` is a hard dependency
        raise GeneratedDocsError(f"could not run `just --summary`: {error}") from error
    if result.returncode != 0:
        raise GeneratedDocsError(
            f"`just --summary` failed in {root}:\n{result.stderr.strip()}"
        )
    return set(result.stdout.split())


def check_arrangement(banners: dict[Path, str], recipes: set[str]) -> list[str]:
    """The reverse direction: dangling banners and orphaned regeneration recipes."""
    errors = [
        f"{path}: names `just {recipe}`, but the justfile defines no such recipe"
        for path, recipe in sorted(banners.items())
        if recipe not in recipes
    ]
    named = set(banners.values())
    errors.extend(
        f"recipe {recipe!r} regenerates documentation, but no generated document "
        f"names it; either it is orphaned or its output lost its banner"
        for recipe in sorted(recipes)
        if _REGENERATION_RECIPE.match(recipe) and recipe not in named
    )
    return errors


def scratch_tree(root: Path, destination: Path) -> None:
    """Copy *root* to *destination* without ``docs/``, with ``.venv`` symlinked.

    The top-level ``docs/`` is left out so a command that writes nothing cannot be
    mistaken for a command that wrote what was already there. A generator therefore
    may not read the documentation tree -- ADR 0098 §5 -- which follows anyway from
    generating out of the source of truth rather than out of another document. A
    ``docs/`` nested anywhere else is ordinary content and is copied.
    """

    def ignore(directory: str, names: list[str]) -> set[str]:
        at_root = Path(directory) == root
        return {
            name
            for name in names
            if name in _PRUNED_ANYWHERE
            or (at_root and (name in _PRUNED_AT_ROOT or name == _DOCS))
        }

    try:
        shutil.copytree(root, destination, ignore=ignore, symlinks=True)
        venv = root / ".venv"
        if venv.exists():
            (destination / ".venv").symlink_to(venv)
    except (OSError, shutil.Error) as error:
        raise GeneratedDocsError(
            f"could not copy {root} into a scratch tree: {error}"
        ) from error


def regenerate(command: str, workspace: Path) -> None:
    """Run *command* in *workspace*, raising when it does not succeed.

    The child gets its own process group so a timeout can kill everything it
    started. Killing only the direct child leaves a grandchild holding the output
    pipe, and the guard would then wait on that pipe forever.
    """
    try:
        process = subprocess.Popen(  # noqa: S603 - argv from a matched banner, no shell
            shlex.split(command),
            cwd=workspace,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            start_new_session=True,
        )
    except OSError as error:
        raise GeneratedDocsError(f"could not run `{command}`: {error}") from error

    with process:
        try:
            output = process.communicate(timeout=_TIMEOUT_SECONDS)[0]
        except subprocess.TimeoutExpired:
            os.killpg(process.pid, signal.SIGKILL)
            process.communicate()
            raise GeneratedDocsError(
                f"`{command}` did not finish within {_TIMEOUT_SECONDS}s"
            ) from None

    if process.returncode != 0:
        raise GeneratedDocsError(
            f"`{command}` failed with exit status {process.returncode} in a scratch "
            f"copy of the tree with {_DOCS}/ removed:\n{output.strip()}"
        )


def compare(
    root: Path, command: str, claimed: set[Path], produced: dict[Path, bytes]
) -> list[str]:
    """Every way the committed tree differs from what *command* just produced."""
    errors = [
        f"{path}: names `{command}`, but that command did not produce it. Either "
        f"the command no longer generates it or the document outlived its generator."
        for path in sorted(claimed - set(produced))
    ]
    diffs = 0
    for path, generated in sorted(produced.items()):
        committed = root / path
        if not committed.is_file():
            errors.append(
                f"{path}: produced by `{command}` but not committed. Run "
                f"`{command}` and commit the result."
            )
            continue
        current = committed.read_bytes()
        if current != generated:
            diffs += 1
            errors.append(_stale(path, command, current, generated, diffs))
        errors.extend(_banner_check(path, command, generated))
    return errors


def _stale(
    path: Path, command: str, committed: bytes, generated: bytes, seen: int
) -> str:
    header = f"stale: {path} differs from what `{command}` produces"
    if seen > _MAX_DIFFS:
        return header
    try:
        diff = difflib.unified_diff(
            committed.decode("utf-8").splitlines(keepends=True),
            generated.decode("utf-8").splitlines(keepends=True),
            fromfile=f"{path} (committed)",
            tofile=f"{path} (generated)",
        )
    except UnicodeDecodeError:  # pragma: no cover - no binary surface today
        return header
    return f"{header}\n{''.join(diff)}"


def _banner_check(path: Path, command: str, generated: bytes) -> list[str]:
    """A generated Markdown file must stamp the command that regenerates it."""
    if path.suffix != ".md":
        return []
    first = generated.decode("utf-8", errors="replace").split("\n", 1)[0].strip()
    match = _BANNER.match(first)
    if match is not None and f"just {match['recipe']}" == command:
        return []
    return [
        f"{path}: produced by `{command}` but its first line does not name that "
        f"command in a generation banner, so nothing would ever check it"
    ]


def check_command(root: Path, command: str, claimed: set[Path]) -> list[str]:
    """Regenerate *command*'s output in a scratch tree and compare it to *root*.

    A command that cannot be run is this command's failure, not the run's: the other
    commands are still checked, so one broken generator does not hide every other
    difference in the tree.
    """
    with tempfile.TemporaryDirectory(prefix="check-generated-docs-") as scratch:
        workspace = Path(scratch) / "tree"
        try:
            scratch_tree(root, workspace)
            regenerate(command, workspace)
        except GeneratedDocsError as error:
            return [str(error)]
        docs = workspace / _DOCS
        produced = {
            path.relative_to(workspace): path.read_bytes()
            for path in sorted(docs.rglob("*"))
            if path.is_file()
        }
    return compare(root, command, claimed, produced)


def check(root: Path) -> tuple[list[str], dict[Path, str]]:
    """Every failure in *root*, plus the banners the walk found."""
    if not (root / _DOCS).is_dir():
        raise GeneratedDocsError(f"documentation directory not found: {root / _DOCS}")
    if not (root / "justfile").is_file():
        raise GeneratedDocsError(f"justfile not found: {root / 'justfile'}")

    banners, errors = read_banners(root)
    recipes = just_recipes(root)
    errors.extend(check_arrangement(banners, recipes))
    if not banners:
        errors.append(
            f"no generated document was found under {root / _DOCS}. Nothing here "
            f"declares a generation banner, so every freshness claim this guard "
            f"makes would be vacuous. A generated surface that was deleted and "
            f"hand-written back looks exactly like this."
        )

    claimed: dict[str, set[Path]] = defaultdict(set)
    for path, recipe in banners.items():
        if recipe in recipes:
            claimed[f"just {recipe}"].add(path)
    for command, paths in sorted(claimed.items()):
        errors.extend(check_command(root, command, paths))
    return errors, banners


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=_REPO_ROOT,
        help=f"repository to check (default: {_REPO_ROOT})",
    )
    args = parser.parse_args(argv)
    root: Path = args.repo_root.resolve()

    try:
        errors, banners = check(root)
    except GeneratedDocsError as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 1

    if errors:
        print(
            f"ERROR: generated documentation check failed for {root}:\n",
            file=sys.stderr,
        )
        for problem in errors:
            print(f"  {problem}", file=sys.stderr)
        return 1

    commands = ", ".join(sorted({f"`just {recipe}`" for recipe in banners.values()}))
    print(
        f"OK: {len(banners)} generated document(s) under {root / _DOCS} match "
        f"{commands}."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
