#!/usr/bin/env python3
"""Guard: every generated document under ``docs/`` is current, and the arrangement
that produces it is intact. See ADR 0098.

A generated document declares itself on its first line::

    <!-- Generated by <script>; do not edit. Regenerate: just <name>-docs -->

That banner is the whole registration for a tracked Markdown file under ``docs/``.
This guard reads it, so the set of generated documents and the command that rebuilds
each of them are derived from the tree rather than restated in a list somebody has to
remember to edit.

The tree here is ``git ls-files``, not the directory listing. What CI will check out
is what the repository tracks, so a page the generator wrote and nobody staged is
reported rather than quietly making the local run green, and a vendored or ignored
document cannot redden a gate for a file that is not in the repository.

For every distinct regeneration command the guard copies the tracked files into a
temporary directory **without the top-level ``docs/``**, runs the command there, and
compares what it produced against what is tracked. Executing is the point: a recipe
whose body is ``true`` produces nothing, so every document naming it is reported.
Starting from an empty ``docs/`` is equally deliberate -- copying the tracked pages
in first would let a no-op command pass by leaving them alone.

The check runs in both directions:

* a tracked document its command did not produce, or produced differently;
* a produced file that is not tracked, or is tracked with different bytes;
* a produced Markdown file carrying no banner, which would be an unwalked document;
* a banner naming a recipe the justfile does not define;
* a recipe named ``*-docs`` that no banner names -- the deletion catch;
* a banner on a Markdown file outside ``docs/``, which nothing here would check.

Finding no banner at all fails too. A universal claim over an empty set is true and
worthless, so an emptied walk reddens rather than passing.

Usage:
    python scripts/check_generated_docs.py [--repo-root <path>]

The guard itself needs ``git`` and ``just``. The recipes it runs need whatever they
need -- for this repository, ``uv`` and a populated ``.venv``. Exits 0 when every
check passes; exits 1 and names each failure otherwise.
"""

from __future__ import annotations

import argparse
import contextlib
import difflib
import os
import re
import shlex
import shutil
import signal
import subprocess
import sys
import tempfile
from collections import defaultdict
from collections.abc import Iterable
from pathlib import Path

# Resolve the repo root relative to this script so the guard can be run from any
# working directory, exactly as scripts/check_adr_numbering.py does.
_SCRIPT_DIR = Path(__file__).resolve().parent
_REPO_ROOT = _SCRIPT_DIR.parent

# One convention, written once. The banner's recipe group and the orphan clause's
# recipe test are the same set by construction, which is what makes the two
# directions exact inverses rather than two rules that have to be kept in step.
#
# The `*-docs` suffix is a safety boundary, not only a name (ADR 0098 §2a). The guard
# *executes* what the banner names and a banner is a file's first line, so this pattern
# decides which recipes a tracked Markdown file can name -- it is why a first line cannot
# name `setup`. It does not bound what those recipes reach: `just` runs a recipe's
# dependencies, so `api-docs: setup` gets there anyway and nothing here would see it.
# Naming a recipe `*-docs` is therefore what makes it executable by anyone who can land a
# Markdown file here, and it obliges that recipe and its whole dependency chain to be
# side-effect-free and deterministic -- producing nothing but its own
# `docs/`, which is narrower than "the tree it runs in" because `scratch_tree` symlinks
# `.venv` and this project is installed editable, so a write through either reaches the
# real checkout -- and to read no secret, because every gate that compares generated bytes
# quotes them into CI logs: `regenerate`'s failure message, `_stale`'s diff, and a
# `*-docs-check` recipe's own diff (ADR 0098 §6) alike. A recipe that publishes, uploads,
# or deploys must not carry this suffix -- and a `[private]` one is invisible to
# `just --summary`, so it escapes the orphan clause here while still running as a
# dependency. Nothing here checks any of that, and `compare` catches only nondeterminism
# prompter than the gap between generating a page and checking it; ADR 0098 §4 records the
# rest as a review obligation, one that lands after the recipe has already run on CI.
_RECIPE = r"[a-z][a-z0-9-]*-docs"
_BANNER = re.compile(
    r"^<!-- Generated by (?P<generator>\S+); do not edit\. "
    rf"Regenerate: just (?P<recipe>{_RECIPE}) -->$"
)
# A first line trying to be a banner and failing. Anchored on the comment opener so
# a page merely *titled* "Reports generated by the nightly export" is prose, not a
# near miss; without the clause entirely, a typo would quietly remove a document
# from the walked set instead of reporting a problem.
_BANNER_HINT = re.compile(r"^<!--.*(?:generated by|do not edit)", re.IGNORECASE)
# ADR 0098 §3: the naming convention that makes the deletion catch possible.
_REGENERATION_RECIPE = re.compile(rf"^{_RECIPE}$")

_DOCS = "docs"
# Comfortably inside the 20-minute CI job, so a hung generator is reported as a
# timeout naming the command that hung rather than as a cancelled job.
_TIMEOUT_SECONDS = 600
# Neither `git ls-files` nor `just --summary` does real work; a minute is already
# far past "something is wrong".
_QUERY_TIMEOUT_SECONDS = 60
# How many differing files get a full diff before the rest are only named. A change
# to a generator's output format makes every page differ at once, and 35 whole-file
# diffs on each of eight CI legs buries the one line saying what to do about it.
_MAX_DIFFS = 3


class GeneratedDocsError(RuntimeError):
    """A failure carrying its own written message, rather than a traceback.

    Two kinds, distinguished by where they are caught. Raised from ``check``'s
    preconditions -- the tree is not a repository, the justfile is gone -- it stops
    the run, because nothing can be checked. Raised from anywhere inside
    ``check_command`` -- the scratch copy failed, the command could not be run, it
    timed out, it exited non-zero -- it becomes that one command's finding, so one
    broken generator does not hide every difference in the rest of the tree.
    """


def tracked_files(root: Path) -> list[Path]:
    """Every path *root* tracks, as paths relative to it."""
    result = _query(["git", "ls-files", "-z"], root)
    tracked = [Path(name) for name in result.split("\0") if name]
    if not tracked:
        raise GeneratedDocsError(
            f"{root} tracks no files; the guard checks what the repository holds, "
            f"and there is nothing here to check."
        )
    return tracked


def just_recipes(root: Path) -> set[str]:
    """The justfile's recipe names, from ``just`` rather than from a regex."""
    return set(_query(["just", "--summary"], root).split())


def _query(command: list[str], root: Path) -> str:
    """Run a read-only command in *root* and return its stdout, or raise."""
    printable = " ".join(command)
    try:
        result = subprocess.run(  # noqa: S603 - fixed argv, no shell
            command,
            cwd=root,
            capture_output=True,
            text=True,
            errors="replace",
            timeout=_QUERY_TIMEOUT_SECONDS,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired) as error:
        raise GeneratedDocsError(
            f"could not run `{printable}` in {root}: {error}"
        ) from error
    if result.returncode != 0:
        raise GeneratedDocsError(
            f"`{printable}` failed in {root}:\n{result.stderr.strip()}"
        )
    return result.stdout


def read_banners(
    root: Path, tracked: Iterable[Path]
) -> tuple[dict[Path, str], list[str]]:
    """Every generated document in *root*, mapped to its regeneration recipe.

    Only the first line is read. A record that quotes the banner format inside its
    prose -- ADR 0098 does -- is not a generated document, and reading further would
    make it one.
    """
    banners: dict[Path, str] = {}
    errors: list[str] = []
    for relative in sorted(tracked):
        path = root / relative
        # Case-folded: a page named `.MD` is still a document, and skipping it
        # silently would be one more way out of the walked set.
        if relative.suffix.lower() != ".md" or not path.is_file():
            continue
        first = _first_line(path)
        match = _BANNER.match(first)
        if match is None:
            if _BANNER_HINT.match(first):
                errors.append(
                    f"{relative}: first line looks like a generation banner but does "
                    f"not match '<!-- Generated by <script>; do not edit. Regenerate: "
                    f"just <name>-docs -->'; a near miss would silently leave the "
                    f"document unchecked"
                )
            continue
        if relative.parts[0] != _DOCS:
            errors.append(
                f"{relative}: carries a generation banner but lives outside "
                f"{_DOCS}/, where this guard does not look. Move it under {_DOCS}/ "
                f"or take the banner off."
            )
            continue
        banners[relative] = match["recipe"]
    return banners, errors


def _first_line(path: Path) -> str:
    with path.open(encoding="utf-8", errors="replace") as handle:
        return handle.readline().strip()


def check_arrangement(banners: dict[Path, str], recipes: set[str]) -> list[str]:
    """The reverse direction: dangling banners and orphaned regeneration recipes."""
    errors = [
        f"{path}: names `just {recipe}`, but the justfile defines no such recipe"
        for path, recipe in sorted(banners.items())
        if recipe not in recipes
    ]
    named = set(banners.values())
    errors.extend(
        f"recipe {recipe!r} regenerates documentation, but no generated document "
        f"names it; either it is orphaned or its output lost its banner"
        for recipe in sorted(recipes)
        if _REGENERATION_RECIPE.match(recipe) and recipe not in named
    )
    return errors


def scratch_tree(root: Path, destination: Path, tracked: Iterable[Path]) -> None:
    """Copy *root*'s tracked files to *destination*, minus the top-level ``docs/``.

    ``docs/`` is left out so a command that writes nothing cannot be mistaken for a
    command that wrote what was already there. A ``docs`` directory nested anywhere
    else is ordinary content and is copied.

    Copying what git tracks rather than what the directory holds keeps caches, build
    output, and a developer's ``.env`` out of the temporary directory, and needs no
    hand-maintained mirror of ``.gitignore`` to do it. ``.venv`` is symlinked, so the
    command runs against the environment that is already installed -- which is also
    why the isolation here is of the working directory only (ADR 0098 §5).
    """
    try:
        destination.mkdir(parents=True, exist_ok=True)
        for relative in tracked:
            source = root / relative
            if relative.parts[0] == _DOCS or not source.is_file():
                continue
            target = destination / relative
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(source, target)
        venv = root / ".venv"
        if venv.exists():
            (destination / ".venv").symlink_to(venv)
    except OSError as error:
        raise GeneratedDocsError(
            f"could not build a scratch copy of {root}: {error}"
        ) from error


def regenerate(command: str, workspace: Path) -> None:
    """Run *command* in *workspace*, raising when it does not succeed.

    The child gets its own process group so a timeout can kill everything it
    started. Killing only the direct child leaves its descendants running, and both
    consequences were measured: they outlive the guard, and they keep the output
    pipe open, so the drain in ``_kill_group`` waits out its whole budget for
    nothing. (``subprocess.run``'s own timeout handling does not hang here -- on
    POSIX it reaps with ``wait()`` rather than reading the pipe -- it just leaks the
    descendants silently and discards the output.)
    """
    try:
        process = subprocess.Popen(  # noqa: S603 - argv from a matched banner, no shell
            shlex.split(command),
            cwd=workspace,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            errors="replace",
            start_new_session=True,
        )
    except OSError as error:
        raise GeneratedDocsError(f"could not run `{command}`: {error}") from error

    with process:
        try:
            output = process.communicate(timeout=_TIMEOUT_SECONDS)[0]
        except subprocess.TimeoutExpired:
            _kill_group(process)
            raise GeneratedDocsError(
                f"`{command}` did not finish within {_TIMEOUT_SECONDS}s"
            ) from None

    if process.returncode != 0:
        # The whole captured output goes into the message, and the message lands in CI
        # logs. This is the rarest of the paths that put a generator's bytes there:
        # `_stale` prints a diff of the generated content on a *successful* run, and a
        # `*-docs-check` recipe prints one from the generator itself, so a generator that
        # embeds a credential in a page discloses it without ever failing. That is why
        # "a `*-docs` recipe must not read a secret" is a constraint on the generator
        # rather than a tidiness rule here (ADR 0098 §2a): truncating any of these bounds
        # the volume and not the disclosure, since a credential inside any retained prefix
        # still reaches the log. The whole output is what makes a failed generator
        # diagnosable; what it may read is the control.
        raise GeneratedDocsError(
            f"`{command}` failed with exit status {process.returncode} in a scratch "
            f"copy of the tree with {_DOCS}/ removed:\n{output.strip()}"
        )


def _kill_group(process: subprocess.Popen[str]) -> None:
    """Kill the timed-out command and everything it started.

    Nothing is read off the pipe afterwards. Measured against a descendant that
    escaped the group by calling ``setsid`` itself and kept the pipe open: draining
    cost the whole drain budget (6.01s for a 1s timeout and a 5s drain) to collect
    output this path discards, while skipping it cost 1.00s, and an in-group
    descendant was 1.00s either way. So the drain could only ever make the timeout
    less of a ceiling. ``Popen.__exit__`` closes this end of the pipe -- which does
    not block -- and waits on the direct child, which the group kill has ended.
    """
    with contextlib.suppress(ProcessLookupError, PermissionError):
        os.killpg(process.pid, signal.SIGKILL)
    # The group kill covers the direct child, so this is the fallback for the one
    # case that misses it: signalling the group was refused. `__exit__` waits on
    # that child without a bound, so it must not still be running.
    with contextlib.suppress(ProcessLookupError):
        process.kill()


def compare(
    root: Path,
    command: str,
    claimed: set[Path],
    produced: dict[Path, bytes],
    tracked: set[Path],
) -> list[str]:
    """Every way the tracked tree differs from what *command* just produced."""
    errors = [
        f"{path}: names `{command}`, but that command did not produce it. Either "
        f"the command no longer generates it or the document outlived its generator."
        for path in sorted(claimed - set(produced))
    ]
    diffs = 0
    for path, generated in sorted(produced.items()):
        source = root / path
        # Membership in the tracked set, not mere presence on disk: a page the
        # generator wrote and nobody staged is absent from what CI will check out.
        if path not in tracked:
            errors.append(
                f"{path}: produced by `{command}` but not tracked by git. Run "
                f"`{command}`, then `git add` the result."
            )
            continue
        if not source.is_file():
            errors.append(
                f"{path}: produced by `{command}` and tracked by git, but missing "
                f"from the working tree. Run `{command}` to restore it, or `git rm` "
                f"it and take its generator with it."
            )
            continue
        current = source.read_bytes()
        if current != generated:
            diffs += 1
            errors.append(_stale(path, command, current, generated, diffs))
        errors.extend(_banner_check(path, command, generated))
    return errors


def _stale(
    path: Path, command: str, tracked: bytes, generated: bytes, seen: int
) -> str:
    header = f"stale: {path} differs from what `{command}` produces"
    if seen > _MAX_DIFFS:
        return header
    try:
        diff = difflib.unified_diff(
            tracked.decode("utf-8").splitlines(keepends=True),
            generated.decode("utf-8").splitlines(keepends=True),
            fromfile=f"{path} (tracked)",
            tofile=f"{path} (generated)",
        )
    except UnicodeDecodeError:  # pragma: no cover - no binary surface today
        return header
    return f"{header}\n{''.join(diff)}"


def _banner_check(path: Path, command: str, generated: bytes) -> list[str]:
    """A generated Markdown file must stamp the command that regenerates it.

    Case-folded to match the walk. Testing the suffix exactly here while the walk
    folds it left `QUIET.MD` produced with no banner accepted in silence -- the
    unbannered-output clause skipped it, and the walk had nothing to register.
    """
    if path.suffix.lower() != ".md":
        return []
    first = generated.decode("utf-8", errors="replace").split("\n", 1)[0].strip()
    match = _BANNER.match(first)
    if match is not None and f"just {match['recipe']}" == command:
        return []
    return [
        f"{path}: produced by `{command}` but its first line does not name that "
        f"command in a generation banner, so nothing would ever check it"
    ]


def check_command(
    root: Path, command: str, claimed: set[Path], tracked: list[Path]
) -> list[str]:
    """Regenerate *command*'s output in a scratch tree and compare it to *root*.

    A command that cannot be run is this command's failure, not the run's: the other
    commands are still checked, so one broken generator does not hide every other
    difference in the tree.
    """
    try:
        with tempfile.TemporaryDirectory(prefix="check-generated-docs-") as scratch:
            workspace = Path(scratch) / "tree"
            scratch_tree(root, workspace, tracked)
            regenerate(command, workspace)
            produced = {
                path.relative_to(workspace): path.read_bytes()
                for path in sorted((workspace / _DOCS).rglob("*"))
                if path.is_file()
            }
    except GeneratedDocsError as error:
        return [str(error)]
    except OSError as error:
        return [f"`{command}` could not be checked: {error}"]
    return compare(root, command, claimed, produced, set(tracked))


def check(root: Path) -> tuple[list[str], dict[Path, str]]:
    """Every failure in *root*, plus the banners the walk found."""
    if not (root / _DOCS).is_dir():
        raise GeneratedDocsError(f"documentation directory not found: {root / _DOCS}")
    if not (root / "justfile").is_file():
        raise GeneratedDocsError(f"justfile not found: {root / 'justfile'}")

    tracked = tracked_files(root)
    banners, errors = read_banners(root, tracked)
    recipes = just_recipes(root)
    errors.extend(check_arrangement(banners, recipes))
    if not banners:
        errors.append(
            f"no generated document was found under {root / _DOCS}. Nothing tracked "
            f"here declares a generation banner, so every freshness claim this guard "
            f"makes would be vacuous. A generated surface that was deleted and "
            f"hand-written back looks exactly like this."
        )

    claimed: dict[str, set[Path]] = defaultdict(set)
    for path, recipe in banners.items():
        if recipe in recipes:
            claimed[f"just {recipe}"].add(path)
    for command, paths in sorted(claimed.items()):
        errors.extend(check_command(root, command, paths, tracked))
    return errors, banners


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=_REPO_ROOT,
        help=f"repository to check (default: {_REPO_ROOT})",
    )
    args = parser.parse_args(argv)
    root: Path = args.repo_root.resolve()

    try:
        errors, banners = check(root)
    except GeneratedDocsError as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 1

    if errors:
        print(
            f"ERROR: generated documentation check failed for {root}:\n",
            file=sys.stderr,
        )
        for problem in errors:
            print(f"  {problem}", file=sys.stderr)
        return 1

    commands = ", ".join(sorted({f"`just {recipe}`" for recipe in banners.values()}))
    print(
        f"OK: {len(banners)} generated document(s) under {root / _DOCS} match "
        f"{commands}."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
