#!/usr/bin/env python3
"""Generate the MCP tool reference under docs/tools/ from the tool registry.

Usage:
    python scripts/gen_tool_reference.py            # write docs/tools/
    python scripts/gen_tool_reference.py --check    # fail if the committed tree is stale

The reference documents every tool in ``TOOL_SECURITY`` -- the registered set, not
the smaller set a default deployment exposes -- so the arbitrary-command escape
hatch is documented where an operator looks for it. See ADR 0097.

Names, summaries and input surfaces come from an MCP ``list_tools()`` walk, the
same walk ``scripts/smoke_mcp.py`` performs; effect, operation and target kind come
from the ``ToolSecurity`` record the registry already holds. No HMC credential is
needed and no network call is made.
"""

from __future__ import annotations

import argparse
import asyncio
import difflib
import sys
from collections.abc import Callable, Iterable, Mapping
from dataclasses import dataclass
from pathlib import Path

from hmc_mcp.access_policy import DEFAULT_CONNECTION_TOKEN
from hmc_mcp.dispatch_scope import dispatch_authorizer
from hmc_mcp.legacy_policy import compile_legacy_policy
from hmc_mcp.server import TOOL_SECURITY, create_mcp
from hmc_mcp.server_command import configure_arbitrary_command_tool
from hmc_mcp.tool_registry import ToolSecurity

# Resolve the repo root relative to this script so the generator can be run from
# any working directory, exactly as scripts/check_env_vars.py does.
_SCRIPT_DIR = Path(__file__).resolve().parent
_REPO_ROOT = _SCRIPT_DIR.parent
_DEFAULT_OUTPUT = _REPO_ROOT / "docs" / "tools"

BANNER = (
    "<!-- Generated by scripts/gen_tool_reference.py; do not edit. "
    "Regenerate: just tool-docs -->"
)

# The 147-vs-148 decision, carried on every page (ADR 0097). Registered, not
# exposed: omitting hmc_run_command would leave the one arbitrary-command tool in
# the package undocumented by its own reference.
SCOPE_NOTE = (
    "This reference covers every tool the server registers, including the ones a "
    "default deployment does not expose."
)

_ENABLEMENT_NOTE = (
    "> Registered but not exposed by a default deployment: {tools}. The server must "
    "be started with `--enable-arbitrary-command` and the selected access policy "
    "must name the tool in a grant's `tools`."
)


class ToolReferenceError(RuntimeError):
    """The registry cannot produce a complete reference.

    Raised rather than emitting a degraded document: a page that silently omits a
    tool, or carries an empty summary cell, reads as authoritative and is not.
    """


@dataclass(frozen=True)
class ToolRecord:
    """One documented tool: its registry classification plus its MCP summary."""

    name: str
    summary: str
    effect: str
    operation: str
    target_kind: str
    exposed_by_default: bool

    @property
    def domain(self) -> str:
        return self.operation.split(".", 1)[0]


def domain_of(record: ToolRecord) -> str:
    """Group a tool by the first segment of its ``operation``.

    The grouping function is a parameter of :func:`render_pages` rather than a
    hardcoded rule, so a later registry field -- a ``tier`` that promotes workflow
    tools above the low-level ones they compose -- becomes a different function
    here and not a rewrite of the renderer. ``_OPERATION`` in ``tool_registry`` is
    private and constrains only the shape, never the vocabulary, so the domain is
    derived from the string rather than imported.
    """
    return record.domain


def build_records(
    descriptions: Mapping[str, str | None],
    security: Mapping[str, ToolSecurity],
    exposed_by_default: Callable[[str], bool],
) -> tuple[ToolRecord, ...]:
    """Join MCP descriptions to registry metadata, or raise.

    *descriptions* is the served surface and *security* the registered one. The two
    must name exactly the same tools: a registered tool the walk did not reach would
    be silently absent from the reference, and a served tool with no record has no
    effect class to publish.
    """
    missing = sorted(set(security) - set(descriptions))
    if missing:
        raise ToolReferenceError(
            f"{len(missing)} registered tool(s) did not reach the generated "
            f"application and would be omitted from the reference: "
            f"{', '.join(missing)}. The reference documents the registered set, so "
            f"fix the composition rather than narrowing the document."
        )
    unknown = sorted(set(descriptions) - set(security))
    if unknown:
        raise ToolReferenceError(
            f"{len(unknown)} exposed tool(s) carry no ToolSecurity record, so their "
            f"effect class and target kind cannot be published: {', '.join(unknown)}."
        )

    records = []
    for name in sorted(security):
        records.append(
            ToolRecord(
                name=name,
                summary=_summary(name, descriptions[name]),
                effect=security[name].effect,
                operation=_operation(name, security[name].operation),
                target_kind=security[name].target_kind,
                exposed_by_default=exposed_by_default(name),
            )
        )
    return tuple(records)


def _summary(name: str, description: str | None) -> str:
    """The first non-empty line of *name*'s description, as one table cell.

    Every tool handler in the package has a multiline docstring, so unlike kdive's
    generator this takes a summary line rather than refusing the newline. A blank
    description raises: the row would otherwise publish an empty cell.
    """
    lines = [line.strip() for line in (description or "").splitlines()]
    summary = next((line for line in lines if line), "")
    if not summary:
        raise ToolReferenceError(
            f"{name}: the MCP description is empty, so the reference would publish "
            f"a row with no summary. Give the handler a docstring whose first line "
            f"describes the tool."
        )
    return summary.replace("|", r"\|")


def _operation(name: str, operation: str) -> str:
    """*operation*, once it is known to yield a non-empty domain segment."""
    domain, _, remainder = operation.partition(".")
    if not domain or not remainder:
        raise ToolReferenceError(
            f"{name}: operation {operation!r} has no 'domain.verb' split, so the "
            f"tool cannot be placed on a page."
        )
    return operation


async def load_descriptions() -> dict[str, str | None]:
    """Every registered tool's MCP description, from a fully granted application.

    Composed with the arbitrary-command tool both granted and enabled, which is
    what makes ``list_tools()`` cover the registered set instead of the default
    deployment's 147. Composition only -- no HMC connection is opened.
    """
    policy = compile_legacy_policy(
        TOOL_SECURITY,
        (DEFAULT_CONNECTION_TOKEN,),
        include_arbitrary_command=True,
    )
    mcp = create_mcp(policy)
    await configure_arbitrary_command_tool(
        True,
        mcp,
        permits=policy.permits_tool,
        authorize=dispatch_authorizer(policy),
    )
    from fastmcp import Client  # noqa: PLC0415 - server extra, imported at use

    async with Client(mcp) as client:
        return {tool.name: tool.description for tool in await client.list_tools()}


def default_exposure() -> Callable[[str], bool]:
    """Whether a default deployment's ceiling reaches a tool by name."""
    default = compile_legacy_policy(TOOL_SECURITY, (DEFAULT_CONNECTION_TOKEN,))
    return default.permits_tool


def render_pages(
    records: Iterable[ToolRecord],
    *,
    group_key: Callable[[ToolRecord], str] = domain_of,
) -> dict[str, str]:
    """The whole reference as ``{relative path: text}``, deterministically.

    Sorted by group and by tool name throughout, with no timestamp, version or
    host in any page, so two runs over one registry produce byte-identical output.
    """
    groups: dict[str, list[ToolRecord]] = {}
    for record in sorted(records, key=lambda item: item.name):
        groups.setdefault(group_key(record), []).append(record)
    pages = {
        f"{group}.md": _render_group(group, members)
        for group, members in sorted(groups.items())
    }
    pages["index.md"] = _render_index(groups)
    return pages


def _render_group(group: str, members: list[ToolRecord]) -> str:
    plural = "" if len(members) == 1 else "s"
    lines = [
        BANNER,
        "",
        f"# `{group}` tools",
        "",
        f"{len(members)} tool{plural} in the `{group}` operation domain. "
        f"{SCOPE_NOTE} See the [tool reference index](index.md) for every domain.",
        "",
        "| Tool | Effect | Operation | Target | Summary |",
        "| --- | --- | --- | --- | --- |",
    ]
    lines.extend(
        f"| `{record.name}` | `{record.effect}` | `{record.operation}` "
        f"| `{record.target_kind}` | {record.summary} |"
        for record in members
    )
    lines.extend(_enablement_note(members))
    lines.append("")
    return "\n".join(lines)


def _enablement_note(members: Iterable[ToolRecord]) -> list[str]:
    """The blockquote naming the tools of *members* a default deployment withholds."""
    withheld = [record.name for record in members if not record.exposed_by_default]
    if not withheld:
        return []
    return ["", _ENABLEMENT_NOTE.format(tools=f"`{'`, `'.join(withheld)}`")]


def _render_index(groups: Mapping[str, list[ToolRecord]]) -> str:
    records = sorted(
        (record for members in groups.values() for record in members),
        key=lambda item: item.name,
    )
    withheld = [record for record in records if not record.exposed_by_default]
    lines = [
        BANNER,
        "",
        "# MCP tool reference",
        "",
        f"{SCOPE_NOTE} It is generated from the server's tool registry, so it "
        "cannot drift from what the code registers.",
        "",
        f"- **{len(records)}** tools are registered.",
        f"- **{len(records) - len(withheld)}** are exposed by a default deployment.",
        "",
        "| Effect class | Tools |",
        "| --- | --- |",
    ]
    lines.extend(
        f"| `{effect}` | {count} |" for effect, count in _effect_counts(records)
    )
    lines.extend([
        "",
        "## Domains",
        "",
        "| Domain | Tools | Page |",
        "| --- | --- | --- |",
    ])
    lines.extend(
        f"| `{group}` | {len(members)} | [{group}.md]({group}.md) |"
        for group, members in sorted(groups.items())
    )
    if withheld:
        lines.extend(["", "## Not exposed by default", *_enablement_note(records)])
    lines.extend([
        "",
        "## Every tool",
        "",
        "| Tool | Effect | Page |",
        "| --- | --- | --- |",
    ])
    lines.extend(
        f"| `{record.name}` | `{record.effect}` "
        f"| [{record.domain}.md]({record.domain}.md) |"
        for record in records
    )
    lines.append("")
    return "\n".join(lines)


def _effect_counts(records: Iterable[ToolRecord]) -> list[tuple[str, int]]:
    counts: dict[str, int] = {}
    for record in records:
        counts[record.effect] = counts.get(record.effect, 0) + 1
    return sorted(counts.items())


def write_pages(pages: Mapping[str, str], output: Path) -> None:
    """Replace *output* with exactly *pages*.

    Markdown files the generator no longer emits are removed: the directory is the
    generator's output, so a page left behind by a renamed domain is stale copy that
    nothing regenerates and nothing deletes.
    """
    output.mkdir(parents=True, exist_ok=True)
    for name, text in sorted(pages.items()):
        (output / name).write_text(text, encoding="utf-8")
    for path in sorted(output.glob("*.md")):
        if path.name not in pages:
            path.unlink()


def check_pages(pages: Mapping[str, str], output: Path) -> list[str]:
    """Every way the committed tree differs from a fresh generation."""
    problems = []
    for name, text in sorted(pages.items()):
        path = output / name
        if not path.is_file():
            problems.append(f"missing: {path}")
            continue
        current = path.read_text(encoding="utf-8")
        if current != text:
            diff = difflib.unified_diff(
                current.splitlines(keepends=True),
                text.splitlines(keepends=True),
                fromfile=f"{path} (committed)",
                tofile=f"{path} (generated)",
            )
            problems.append(f"stale: {path}\n{''.join(diff)}")
    for path in sorted(output.glob("*.md")):
        if path.name not in pages:
            problems.append(f"not generated by this script: {path}")
    return problems


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="report drift and exit 1 instead of writing",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=_DEFAULT_OUTPUT,
        help=f"directory to generate into (default: {_DEFAULT_OUTPUT})",
    )
    args = parser.parse_args(argv)

    records = build_records(
        asyncio.run(load_descriptions()), TOOL_SECURITY, default_exposure()
    )
    pages = render_pages(records)

    if not args.check:
        write_pages(pages, args.output)
        print(f"OK: wrote {len(pages)} pages for {len(records)} tools to {args.output}")
        return 0

    problems = check_pages(pages, args.output)
    if problems:
        print(
            f"ERROR: {args.output} does not match the tool registry:\n",
            file=sys.stderr,
        )
        for problem in problems:
            print(problem, file=sys.stderr)
        print(
            "\nRun `just tool-docs` and commit the result. Do not edit these pages "
            "by hand -- they are generated from src/hmc_mcp.",
            file=sys.stderr,
        )
        return 1
    print(f"OK: {args.output} matches the registry ({len(records)} tools).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
