#!/usr/bin/env python3
"""Generate the MCP tool reference under docs/tools/ from the tool registry.

Usage:
    python scripts/gen_tool_reference.py            # write docs/tools/
    python scripts/gen_tool_reference.py --check    # fail if the committed tree is stale

The reference documents every tool in ``TOOL_SECURITY`` -- the registered set, not
the smaller set a default deployment exposes -- so the arbitrary-command escape
hatch is documented where an operator looks for it. See ADR 0097.

Names and summaries come from an MCP ``list_tools()`` walk, the same walk
``scripts/smoke_mcp.py`` performs; effect, operation and target kind come
from the ``ToolSecurity`` record the registry already holds. No HMC credential is
needed and no network call is made.
"""

from __future__ import annotations

import argparse
import asyncio
import difflib
import sys
from collections.abc import Callable, Iterable, Mapping
from dataclasses import dataclass
from operator import attrgetter
from pathlib import Path

from hmc_mcp.access_policy import DEFAULT_CONNECTION_TOKEN
from hmc_mcp.dispatch_scope import dispatch_authorizer
from hmc_mcp.legacy_policy import compile_legacy_policy
from hmc_mcp.server import TOOL_SECURITY, create_mcp
from hmc_mcp.server_command import configure_arbitrary_command_tool
from hmc_mcp.tool_registry import ToolSecurity

# Resolve the repo root relative to this script so the generator can be run from
# any working directory, exactly as scripts/check_env_vars.py does.
_SCRIPT_DIR = Path(__file__).resolve().parent
_REPO_ROOT = _SCRIPT_DIR.parent
_DEFAULT_OUTPUT = _REPO_ROOT / "docs" / "tools"

BANNER = (
    "<!-- Generated by scripts/gen_tool_reference.py; do not edit. "
    "Regenerate: just tool-docs -->"
)
_INDEX_PAGE = "index.md"
# How many stale pages get a full diff before the rest are only named. A change to
# the row format makes every page stale at once, and 35 whole-file diffs on each of
# eight CI legs buries the one line that says what to do about it.
_MAX_DIFFS = 3

# The 147-vs-148 decision, carried on every page (ADR 0097). Registered, not
# exposed: omitting hmc_run_command would leave the one arbitrary-command tool in
# the package undocumented by its own reference.
SCOPE_NOTE = (
    "This reference covers every tool the server registers, including the ones a "
    "default deployment does not expose."
)

_ENABLEMENT_NOTE = (
    "> Registered but not exposed by a default deployment: {tools}. The server must "
    "be started with `--enable-arbitrary-command` and the selected access policy "
    "must name the tool in a grant's `tools`."
)


class ToolReferenceError(RuntimeError):
    """The registry cannot produce a complete reference.

    Raised rather than emitting a degraded document: a page that silently omits a
    tool, or carries an empty summary cell, reads as authoritative and is not.
    """


@dataclass(frozen=True)
class ToolRecord:
    """One documented tool: its registry classification plus its MCP summary."""

    name: str
    summary: str
    effect: str
    operation: str
    target_kind: str
    exposed_by_default: bool

    @property
    def domain(self) -> str:
        """The operation's first segment.

        Derived from the string rather than imported: ``_OPERATION``
        (``tool_registry.py:46``) is private and constrains only the shape -- two
        lowercase dot-separated segments -- never the vocabulary.
        """
        return self.operation.split(".", 1)[0]


def build_records(
    descriptions: Mapping[str, str | None],
    security: Mapping[str, ToolSecurity],
    exposed_by_default: Callable[[str], bool],
) -> tuple[ToolRecord, ...]:
    """Join MCP descriptions to registry metadata, or raise.

    *descriptions* is the served surface and *security* the registered one. The two
    must name exactly the same tools: a registered tool the walk did not reach would
    be silently absent from the reference, and a served tool with no record has no
    effect class to publish.
    """
    missing = sorted(set(security) - set(descriptions))
    if missing:
        raise ToolReferenceError(
            f"{len(missing)} registered tool(s) did not reach the generated "
            f"application and would be omitted from the reference: "
            f"{', '.join(missing)}. The reference documents the registered set, so "
            f"fix the composition rather than narrowing the document."
        )
    unknown = sorted(set(descriptions) - set(security))
    if unknown:
        raise ToolReferenceError(
            f"{len(unknown)} exposed tool(s) carry no ToolSecurity record, so their "
            f"effect class and target kind cannot be published: {', '.join(unknown)}."
        )

    records = []
    for name in sorted(security):
        records.append(
            ToolRecord(
                name=name,
                summary=_summary(name, descriptions[name]),
                effect=security[name].effect,
                operation=_operation(name, security[name].operation),
                target_kind=security[name].target_kind,
                exposed_by_default=exposed_by_default(name),
            )
        )
    return tuple(records)


def _summary(name: str, description: str | None) -> str:
    """The first non-empty line of *name*'s description, as one table cell.

    Every tool handler in the package has a multiline docstring, so unlike kdive's
    generator this takes a summary line rather than refusing the newline. A blank
    description raises: the row would otherwise publish an empty cell.
    """
    lines = [line.strip() for line in (description or "").splitlines()]
    summary = next((line for line in lines if line), "")
    if not summary:
        raise ToolReferenceError(
            f"{name}: the MCP description is empty, so the reference would publish "
            f"a row with no summary. Give the handler a docstring whose first line "
            f"describes the tool."
        )
    return summary.replace("|", r"\|")


def _operation(name: str, operation: str) -> str:
    """*operation*, once it is known to yield a non-empty domain segment."""
    domain, _, remainder = operation.partition(".")
    if not domain or not remainder:
        raise ToolReferenceError(
            f"{name}: operation {operation!r} has no 'domain.verb' split, so the "
            f"tool cannot be placed on a page."
        )
    return operation


async def load_descriptions() -> dict[str, str | None]:
    """Every registered tool's MCP description, from a fully granted application.

    Composed with the arbitrary-command tool both granted and enabled, which is
    what makes ``list_tools()`` cover the registered set instead of the default
    deployment's 147. Composition only -- no HMC connection is opened.
    """
    policy = compile_legacy_policy(
        TOOL_SECURITY,
        (DEFAULT_CONNECTION_TOKEN,),
        include_arbitrary_command=True,
    )
    mcp = create_mcp(policy)
    await configure_arbitrary_command_tool(
        True,
        mcp,
        permits=policy.permits_tool,
        authorize=dispatch_authorizer(policy),
    )
    from fastmcp import Client  # noqa: PLC0415 - server extra, imported at use

    async with Client(mcp) as client:
        return {tool.name: tool.description for tool in await client.list_tools()}


def default_exposure() -> Callable[[str], bool]:
    """Whether a default deployment's ceiling reaches a tool by name.

    The ceiling only. ``hmc_run_command`` additionally needs
    ``--enable-arbitrary-command``, and today the two gates agree on it because the
    generated policy withholds it as well. A future flag-gated tool the ceiling
    permits would be published here as exposed when it is not; that would need the
    flag's own condition, which lives in ``cli_app`` rather than in any policy.
    """
    default = compile_legacy_policy(TOOL_SECURITY, (DEFAULT_CONNECTION_TOKEN,))
    return default.permits_tool


def render_pages(
    records: Iterable[ToolRecord],
    *,
    # Taken as a parameter because #476 requires the grouping to be pluggable: when
    # a `tier` field arrives to promote workflow tools above the tools they compose,
    # that is a different function here rather than a rewrite of the renderer.
    group_key: Callable[[ToolRecord], str] = attrgetter("domain"),
) -> dict[str, str]:
    """The whole reference as ``{relative path: text}``, deterministically.

    Sorted by group and by tool name throughout, with no timestamp, version or
    host in any page, so two runs over one registry produce byte-identical output.
    """
    groups: dict[str, list[ToolRecord]] = {}
    for record in sorted(records, key=lambda item: item.name):
        groups.setdefault(group_key(record), []).append(record)
    if _INDEX_PAGE.removesuffix(".md") in groups:
        raise ToolReferenceError(
            f"a tool group is named {_INDEX_PAGE.removesuffix('.md')!r}, which "
            f"collides with the {_INDEX_PAGE} the generator writes; that group's "
            f"page would be silently replaced by the index."
        )
    pages = {
        f"{group}.md": _render_group(group, members)
        for group, members in sorted(groups.items())
    }
    pages[_INDEX_PAGE] = _render_index(groups)
    return pages


def _render_group(group: str, members: list[ToolRecord]) -> str:
    plural = "" if len(members) == 1 else "s"
    lines = [
        BANNER,
        "",
        f"# `{group}` tools",
        "",
        f"{len(members)} tool{plural} in the `{group}` operation domain. "
        f"{SCOPE_NOTE} See the [tool reference index](index.md) for every domain.",
        "",
        "| Tool | Effect | Operation | Target | Summary |",
        "| --- | --- | --- | --- | --- |",
    ]
    lines.extend(
        f"| `{record.name}` | `{record.effect}` | `{record.operation}` "
        f"| `{record.target_kind}` | {record.summary} |"
        for record in members
    )
    lines.extend(_enablement_note(members))
    lines.append("")
    return "\n".join(lines)


def _enablement_note(members: Iterable[ToolRecord]) -> list[str]:
    """The blockquote naming the tools of *members* a default deployment withholds."""
    withheld = [record.name for record in members if not record.exposed_by_default]
    if not withheld:
        return []
    return ["", _ENABLEMENT_NOTE.format(tools=f"`{'`, `'.join(withheld)}`")]


def _render_index(groups: Mapping[str, list[ToolRecord]]) -> str:
    records = sorted(
        (record for members in groups.values() for record in members),
        key=lambda item: item.name,
    )
    withheld = [record for record in records if not record.exposed_by_default]
    lines = [
        BANNER,
        "",
        "# MCP tool reference",
        "",
        f"{SCOPE_NOTE} It is generated from the server's tool registry, so it "
        "cannot drift from what the code registers.",
        "",
        f"- **{len(records)}** tools are registered.",
        f"- **{len(records) - len(withheld)}** are exposed by a default deployment.",
        "",
        "| Effect class | Tools |",
        "| --- | --- |",
    ]
    lines.extend(
        f"| `{effect}` | {count} |" for effect, count in _effect_counts(records)
    )
    lines.extend([
        "",
        "## Domains",
        "",
        "| Domain | Tools | Page |",
        "| --- | --- | --- |",
    ])
    lines.extend(
        f"| `{group}` | {len(members)} | [{group}.md]({group}.md) |"
        for group, members in sorted(groups.items())
    )
    if withheld:
        lines.extend(["", "## Not exposed by default", *_enablement_note(records)])
    lines.extend([
        "",
        "## Every tool",
        "",
        "| Tool | Effect | Page |",
        "| --- | --- | --- |",
    ])
    lines.extend(
        f"| `{record.name}` | `{record.effect}` "
        f"| [{record.domain}.md]({record.domain}.md) |"
        for record in records
    )
    lines.append("")
    return "\n".join(lines)


def _effect_counts(records: Iterable[ToolRecord]) -> list[tuple[str, int]]:
    counts: dict[str, int] = {}
    for record in records:
        counts[record.effect] = counts.get(record.effect, 0) + 1
    return sorted(counts.items())


def write_pages(pages: Mapping[str, str], output: Path) -> None:
    """Replace *output* with exactly *pages*.

    A page this generator emitted before but no longer emits -- a renamed domain,
    a domain whose last tool was deleted -- is stale copy that nothing regenerates,
    so it is removed and the removal is reported. A Markdown file the generator did
    **not** write is never deleted: it raises instead, because at that point the
    output directory is not the generator's alone and a wrong ``--output`` would
    otherwise destroy hand-written documentation.
    """
    output.mkdir(parents=True, exist_ok=True)
    for path in sorted(output.glob("*.md")):
        if path.name in pages:
            continue
        if not path.read_text(encoding="utf-8").startswith(BANNER):
            raise ToolReferenceError(
                f"{path} was not written by this script, so {output} is not a "
                f"generated tree. Refusing to delete it; move it aside or point "
                f"--output somewhere else."
            )
        path.unlink()
        print(f"removed page no longer generated: {path}")
    for name, text in sorted(pages.items()):
        (output / name).write_text(text, encoding="utf-8")


def check_pages(pages: Mapping[str, str], output: Path) -> list[str]:
    """Every way the committed tree differs from a fresh generation."""
    problems = []
    stale = 0
    for name, text in sorted(pages.items()):
        path = output / name
        if not path.is_file():
            problems.append(f"missing: {path}")
            continue
        current = path.read_text(encoding="utf-8")
        if current == text:
            continue
        stale += 1
        if stale > _MAX_DIFFS:
            problems.append(f"stale: {path}")
            continue
        diff = difflib.unified_diff(
            current.splitlines(keepends=True),
            text.splitlines(keepends=True),
            fromfile=f"{path} (committed)",
            tofile=f"{path} (generated)",
        )
        problems.append(f"stale: {path}\n{''.join(diff)}")
    for path in sorted(output.glob("*.md")):
        if path.name not in pages:
            problems.append(f"not generated by this script: {path}")
    return problems


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="report drift and exit 1 instead of writing",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=_DEFAULT_OUTPUT,
        help=f"directory to generate into (default: {_DEFAULT_OUTPUT})",
    )
    args = parser.parse_args(argv)

    try:
        records = build_records(
            asyncio.run(load_descriptions()), TOOL_SECURITY, default_exposure()
        )
        pages = render_pages(records)
        if not args.check:
            write_pages(pages, args.output)
            print(
                f"OK: wrote {len(pages)} pages for {len(records)} tools to {args.output}"
            )
            return 0
        problems = check_pages(pages, args.output)
    except ToolReferenceError as error:
        # The messages are written to be read; a traceback around them is noise.
        print(f"ERROR: {error}", file=sys.stderr)
        return 1

    if problems:
        print(
            f"ERROR: {args.output} does not match the tool registry:\n",
            file=sys.stderr,
        )
        for problem in problems:
            print(problem, file=sys.stderr)
        print(
            "\nRun `just tool-docs` and commit the result. Do not edit these pages "
            "by hand -- they are generated from src/hmc_mcp.",
            file=sys.stderr,
        )
        return 1
    print(f"OK: {args.output} matches the registry ({len(records)} tools).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
