"""Tests for the generated-documentation guardrail (scripts/check_generated_docs.py).

Every clause of ADR 0098 §3 gets a negative control here: the guard is only worth
having if each of its five failures, and the non-vacuity condition, can be shown to
bite. The synthetic trees carry a throwaway generator whose output is read from
``pages.json``, so what a command *produces* can be varied independently of what is
*committed* -- which is the whole comparison the guard makes.
"""

from __future__ import annotations

import importlib.util
import json
import shutil
from pathlib import Path

MODULE_PATH = Path(__file__).parents[2] / "scripts" / "check_generated_docs.py"
MODULE_SPEC = importlib.util.spec_from_file_location(
    "check_generated_docs", MODULE_PATH
)
assert MODULE_SPEC is not None
assert MODULE_SPEC.loader is not None
check_generated_docs = importlib.util.module_from_spec(MODULE_SPEC)
MODULE_SPEC.loader.exec_module(check_generated_docs)

ROOT = Path(__file__).parents[2]

BANNER = "<!-- Generated by gen.py; do not edit. Regenerate: just demo-docs -->"
JUSTFILE = "demo-docs:\n    python3 gen.py\n"
# Reads what to write from a data file so a test can make the generator and the
# committed tree disagree without editing any code.
GENERATOR = """\
import json
import pathlib

pages = json.loads(pathlib.Path("pages.json").read_text(encoding="utf-8"))
out = pathlib.Path("docs/generated")
out.mkdir(parents=True, exist_ok=True)
for name, text in pages.items():
    (out / name).write_text(text, encoding="utf-8")
"""


def _page(body: str, banner: str = BANNER) -> str:
    return f"{banner}\n\n{body}\n"


def _tree(
    tmp_path: Path,
    *,
    produced: dict[str, str] | None = None,
    committed: dict[str, str] | None = None,
    justfile: str = JUSTFILE,
) -> Path:
    """A minimal repository: a justfile, a generator, and a committed docs tree."""
    healthy = {"page.md": _page("# demo")}
    root = tmp_path / "repo"
    (root / "docs" / "generated").mkdir(parents=True)
    (root / "justfile").write_text(justfile, encoding="utf-8")
    (root / "gen.py").write_text(GENERATOR, encoding="utf-8")
    (root / "pages.json").write_text(
        json.dumps(healthy if produced is None else produced), encoding="utf-8"
    )
    for name, text in (healthy if committed is None else committed).items():
        (root / "docs" / "generated" / name).write_text(text, encoding="utf-8")
    return root


def _run(root: Path) -> int:
    return check_generated_docs.main(["--repo-root", str(root)])


def _tool_reference_only(tmp_path: Path, justfile: str) -> Path:
    """The repository's real justfile and real docs/tools/, and nothing else.

    Enough for the guard to derive recipes and banners from committed production
    configuration. Nothing here can run the real generator, so only tests whose
    regeneration command is stubbed or unreachable may use it.
    """
    root = tmp_path / "repo"
    (root / "docs").mkdir(parents=True)
    (root / "justfile").write_text(justfile, encoding="utf-8")
    shutil.copytree(ROOT / "docs" / "tools", root / "docs" / "tools")
    return root


# --- the committed repository ------------------------------------------------


def test_passes_on_the_committed_repository(capsys) -> None:
    """End to end: run every declared regeneration command and diff the result."""
    assert check_generated_docs.main([]) == 0
    out = capsys.readouterr().out
    assert "`just tool-docs`" in out
    assert str(ROOT / "docs") in out


def test_stubbing_the_real_regeneration_recipe_reddens(tmp_path, capsys) -> None:
    """Negative control on production configuration: `tool-docs: true` reddens.

    The rejected design in #480 asserted that a freshness recipe was *wired*. This
    is the difference: the recipe is still wired, still named by every banner, and
    still runs -- it just does nothing, and that is caught.
    """
    justfile = (ROOT / "justfile").read_text(encoding="utf-8")
    stubbed = justfile.replace(
        "tool-docs:\n    uv run --no-sync python scripts/gen_tool_reference.py\n",
        "tool-docs:\n    true\n",
    )
    assert stubbed != justfile

    assert _run(_tool_reference_only(tmp_path, stubbed)) == 1
    err = capsys.readouterr().err
    assert "docs/tools/index.md" in err
    assert "just tool-docs" in err


def test_deleting_the_real_generated_surface_reddens(tmp_path, capsys) -> None:
    """The other direction on production configuration: no document, orphaned recipe.

    Deleting docs/tools/ and hand-writing a replacement with no banner is the hole
    the rejected design left open; here it empties the walk and orphans `tool-docs`.
    """
    root = _tool_reference_only(tmp_path, (ROOT / "justfile").read_text())
    shutil.rmtree(root / "docs" / "tools")
    (root / "docs" / "tools-summary.md").write_text("# hand written\n", encoding="utf-8")

    assert _run(root) == 1
    err = capsys.readouterr().err
    assert "tool-docs" in err
    assert "no generated document" in err


# --- the healthy synthetic tree ----------------------------------------------


def test_passes_on_a_healthy_tree(tmp_path, capsys) -> None:
    assert _run(_tree(tmp_path)) == 0
    assert "`just demo-docs`" in capsys.readouterr().out


def test_content_checks_over_prose_are_not_pulled_into_the_walk(tmp_path) -> None:
    """ADR 0098 §1b: a guard over judgement-carrying prose carries no banner.

    `env-vars` and `nicknames` check facts embedded in hand-written documents. They
    are not regeneration recipes, so no banner may be required to name them.
    """
    justfile = (
        "env-vars:\n    python3 -c 'pass'\n\n"
        "nicknames:\n    python3 -c 'pass'\n\n"
        "demo-docs-check:\n    python3 -c 'pass'\n\n" + JUSTFILE
    )

    assert _run(_tree(tmp_path, justfile=justfile)) == 0


# --- negative controls: freshness (ADR 0098 §3, forward) ---------------------


def test_stubbed_recipe_reddens(tmp_path, capsys) -> None:
    """A recipe whose body is `true` produces nothing, so its document is unclaimed."""
    assert _run(_tree(tmp_path, justfile="demo-docs:\n    true\n")) == 1
    err = capsys.readouterr().err
    assert "docs/generated/page.md" in err
    assert "did not produce" in err


def test_stale_committed_document_reddens(tmp_path, capsys) -> None:
    """A hand edit to a generated page is a difference, and the diff is shown."""
    root = _tree(tmp_path, committed={"page.md": _page("# edited by hand")})

    assert _run(root) == 1
    err = capsys.readouterr().err
    assert "stale" in err
    assert "edited by hand" in err
    assert "just demo-docs" in err


def test_generated_output_that_is_not_committed_reddens(tmp_path, capsys) -> None:
    """The registry grew a page and nobody regenerated: the new page is missing."""
    root = _tree(
        tmp_path,
        produced={"page.md": _page("# demo"), "extra.md": _page("# extra")},
    )

    assert _run(root) == 1
    err = capsys.readouterr().err
    assert "docs/generated/extra.md" in err
    assert "not committed" in err


def test_generated_output_without_a_banner_reddens(tmp_path, capsys) -> None:
    """A generated page with no banner is a document the walk cannot see."""
    pages = {"page.md": _page("# demo"), "quiet.md": "# no banner\n"}
    root = _tree(tmp_path, produced=pages, committed=pages)

    assert _run(root) == 1
    err = capsys.readouterr().err
    assert "docs/generated/quiet.md" in err
    assert "banner" in err


def test_failing_regeneration_command_is_reported(tmp_path, capsys) -> None:
    """A command that exits non-zero is a failure with its output, not a diff."""
    assert _run(_tree(tmp_path, justfile="demo-docs:\n    exit 3\n")) == 1
    err = capsys.readouterr().err
    assert "just demo-docs" in err
    assert "failed" in err


# --- negative controls: the arrangement (ADR 0098 §3, reverse) ---------------


def test_dangling_banner_reddens(tmp_path, capsys) -> None:
    """Delete the recipe and the banner that names it dangles."""
    root = _tree(tmp_path, justfile="other:\n    true\n")

    assert _run(root) == 1
    err = capsys.readouterr().err
    assert "docs/generated/page.md" in err
    assert "demo-docs" in err
    assert "no such recipe" in err


def test_orphaned_regeneration_recipe_reddens(tmp_path, capsys) -> None:
    """A `*-docs` recipe no banner names generates nothing that is checked."""
    root = _tree(tmp_path, justfile=JUSTFILE + "\nextra-docs:\n    true\n")

    assert _run(root) == 1
    err = capsys.readouterr().err
    assert "extra-docs" in err
    assert "no generated document names it" in err
    # The recipe that *is* named is not reported as orphaned.
    assert "'demo-docs'" not in err


def test_deleting_the_only_generated_document_reddens(tmp_path, capsys) -> None:
    """Both reverse clauses fire: the walk is empty and the recipe is orphaned."""
    root = _tree(tmp_path)
    (root / "docs" / "generated" / "page.md").unlink()

    assert _run(root) == 1
    err = capsys.readouterr().err
    assert "no generated document" in err
    assert "demo-docs" in err


# --- banner grammar ----------------------------------------------------------


def test_malformed_banner_reddens(tmp_path, capsys) -> None:
    """A near-miss banner fails rather than dropping out of the walked set."""
    broken = "<!-- Generated by gen.py; do not edit -->"
    root = _tree(
        tmp_path,
        produced={"page.md": _page("# demo", broken)},
        committed={"page.md": _page("# demo", broken)},
    )

    assert _run(root) == 1
    err = capsys.readouterr().err
    assert "docs/generated/page.md" in err
    assert "Regenerate:" in err


def test_banner_naming_a_bare_script_reddens(tmp_path, capsys) -> None:
    """ADR 0098 §2: the regeneration command is a just recipe, not a script call."""
    banner = "<!-- Generated by gen.py; do not edit. Regenerate: python3 gen.py -->"
    root = _tree(
        tmp_path,
        produced={"page.md": _page("# demo", banner)},
        committed={"page.md": _page("# demo", banner)},
    )

    assert _run(root) == 1
    assert "docs/generated/page.md" in capsys.readouterr().err


def test_prose_quoting_a_banner_is_not_treated_as_generated(tmp_path) -> None:
    """A record explaining the banner format carries it below its own first line.

    ADR 0098 quotes the exact banner inside a fenced block. Reading only the first
    line is what keeps that record out of the walk.
    """
    root = _tree(tmp_path)
    (root / "docs" / "note.md").write_text(
        f"# About banners\n\n```\n{BANNER}\n```\n", encoding="utf-8"
    )

    assert _run(root) == 0


# --- operating conditions ----------------------------------------------------


def test_missing_docs_directory_fails(tmp_path, capsys) -> None:
    """A moved documentation tree fails rather than passing over nothing."""
    root = _tree(tmp_path)
    shutil.rmtree(root / "docs")

    assert _run(root) == 1
    assert "not found" in capsys.readouterr().err


def test_missing_justfile_fails(tmp_path, capsys) -> None:
    """Without the justfile neither direction of the check can be derived."""
    root = _tree(tmp_path)
    (root / "justfile").unlink()

    assert _run(root) == 1
    assert "justfile" in capsys.readouterr().err
