"""Tests for the generated-documentation guardrail (scripts/check_generated_docs.py).

Every clause of ADR 0098 §3 gets a negative control here: the guard is only worth
having if each of its failures can be shown to bite. Each control asserts on the
message its own clause emits, not on a substring another clause would also satisfy
-- three of these were vacuous for exactly that reason before review caught it.

The synthetic trees carry a throwaway generator whose output is read from
``pages.json``, so what a command *produces* can be varied independently of what is
*committed*, which is the whole comparison the guard makes.
"""

from __future__ import annotations

import importlib.util
import json
import shutil
import subprocess
import time
from pathlib import Path

import pytest

MODULE_PATH = Path(__file__).parents[2] / "scripts" / "check_generated_docs.py"
MODULE_SPEC = importlib.util.spec_from_file_location(
    "check_generated_docs", MODULE_PATH
)
assert MODULE_SPEC is not None
assert MODULE_SPEC.loader is not None
check_generated_docs = importlib.util.module_from_spec(MODULE_SPEC)
MODULE_SPEC.loader.exec_module(check_generated_docs)

ROOT = Path(__file__).parents[2]

BANNER = "<!-- Generated by gen.py; do not edit. Regenerate: just demo-docs -->"
JUSTFILE = "demo-docs:\n    python3 gen.py\n"
NO_DOCUMENT = "no generated document was found under"
ORPHANED = "no generated document names it"
# Reads what to write from a data file so a test can make the generator and the
# committed tree disagree without editing any code. The nested docs/ read proves the
# guard withholds only the top-level one.
GENERATOR = """\
import json
import pathlib

pages = json.loads(pathlib.Path("pages.json").read_text(encoding="utf-8"))
nested = pathlib.Path("lib/docs/suffix.txt")
suffix = nested.read_text(encoding="utf-8") if nested.is_file() else ""
out = pathlib.Path("docs/generated")
out.mkdir(parents=True, exist_ok=True)
for name, text in pages.items():
    (out / name).write_text(text + suffix, encoding="utf-8")
"""


def _page(body: str, banner: str = BANNER) -> str:
    return f"{banner}\n\n{body}\n"


def _tree(
    tmp_path: Path,
    *,
    produced: dict[str, str] | None = None,
    committed: dict[str, str] | None = None,
    justfile: str = JUSTFILE,
) -> Path:
    """A minimal repository: a justfile, a generator, and a tracked docs tree."""
    healthy = {"page.md": _page("# demo")}
    root = tmp_path / "repo"
    (root / "docs" / "generated").mkdir(parents=True)
    (root / "justfile").write_text(justfile, encoding="utf-8")
    (root / "gen.py").write_text(GENERATOR, encoding="utf-8")
    (root / "pages.json").write_text(
        json.dumps(healthy if produced is None else produced), encoding="utf-8"
    )
    for name, text in (healthy if committed is None else committed).items():
        (root / "docs" / "generated" / name).write_text(text, encoding="utf-8")
    subprocess.run(
        ["git", "init", "-q", "--initial-branch=main"], cwd=root, check=True
    )
    return root


def _stage(root: Path) -> None:
    """Track everything currently in *root*. The guard walks `git ls-files`."""
    subprocess.run(["git", "add", "-A"], cwd=root, check=True, capture_output=True)


def _run(root: Path) -> int:
    """Stage the tree as a developer would, then check it."""
    _stage(root)
    return check_generated_docs.main(["--repo-root", str(root)])


def _tool_reference_only(tmp_path: Path, justfile: str) -> Path:
    """The repository's real justfile and real docs/tools/, and nothing else.

    Enough for the guard to derive recipes and banners from committed production
    configuration. Nothing here can run the real generator, so only tests whose
    regeneration command is stubbed or unreachable may use it.
    """
    root = tmp_path / "repo"
    (root / "docs").mkdir(parents=True)
    (root / "justfile").write_text(justfile, encoding="utf-8")
    shutil.copytree(ROOT / "docs" / "tools", root / "docs" / "tools")
    subprocess.run(
        ["git", "init", "-q", "--initial-branch=main"], cwd=root, check=True
    )
    return root


# --- the committed repository ------------------------------------------------


def test_passes_on_the_committed_repository(capsys) -> None:
    """End to end: run every declared regeneration command and diff the result."""
    assert check_generated_docs.main([]) == 0
    out = capsys.readouterr().out
    assert "`just tool-docs`" in out
    assert str(ROOT / "docs") in out


def test_stubbing_the_real_regeneration_recipe_reddens(tmp_path, capsys) -> None:
    """Negative control on production configuration: `tool-docs: true` reddens.

    The rejected design in #480 asserted that a freshness recipe was *wired*. This
    is the difference: the recipe is still wired, still named by every banner, and
    still runs -- it just does nothing, and that is caught.
    """
    justfile = (ROOT / "justfile").read_text(encoding="utf-8")
    stubbed = justfile.replace(
        "tool-docs:\n    uv run --no-sync python scripts/gen_tool_reference.py\n",
        "tool-docs:\n    true\n",
    )
    assert stubbed != justfile

    assert _run(_tool_reference_only(tmp_path, stubbed)) == 1
    err = capsys.readouterr().err
    assert "docs/tools/index.md: names `just tool-docs`" in err
    assert "did not produce it" in err


def test_deleting_the_real_generated_surface_reddens(tmp_path, capsys) -> None:
    """The other direction on production configuration: no document, orphaned recipe.

    Deleting docs/tools/ and hand-writing a replacement with no banner is the hole
    the rejected design left open; here it empties the walk and orphans `tool-docs`.
    """
    root = _tool_reference_only(tmp_path, (ROOT / "justfile").read_text())
    shutil.rmtree(root / "docs" / "tools")
    (root / "docs" / "tools-summary.md").write_text("# hand written\n", encoding="utf-8")

    assert _run(root) == 1
    err = capsys.readouterr().err
    assert f"'tool-docs' regenerates documentation, but {ORPHANED}" in err
    assert NO_DOCUMENT in err


# --- the healthy synthetic tree ----------------------------------------------


def test_passes_on_a_healthy_tree(tmp_path, capsys) -> None:
    assert _run(_tree(tmp_path)) == 0
    assert "`just demo-docs`" in capsys.readouterr().out


def test_content_checks_over_prose_are_not_pulled_into_the_walk(tmp_path) -> None:
    """ADR 0098 §1b: a guard over judgement-carrying prose carries no banner.

    `env-vars` and `nicknames` check facts embedded in hand-written documents. They
    are not regeneration recipes, so no banner may be required to name them.
    """
    justfile = (
        "env-vars:\n    python3 -c 'pass'\n\n"
        "nicknames:\n    python3 -c 'pass'\n\n"
        "demo-docs-check:\n    python3 -c 'pass'\n\n" + JUSTFILE
    )

    assert _run(_tree(tmp_path, justfile=justfile)) == 0


def test_only_the_top_level_docs_tree_is_withheld(tmp_path) -> None:
    """A nested docs/ is generator input and must survive into the scratch tree.

    Withholding every directory named `docs` would make this generator produce pages
    without the suffix, which is a difference the guard would then report.
    """
    root = _tree(tmp_path, committed={"page.md": _page("# demo") + "extra\n"})
    (root / "lib" / "docs").mkdir(parents=True)
    (root / "lib" / "docs" / "suffix.txt").write_text("extra\n", encoding="utf-8")

    assert _run(root) == 0


# --- negative controls: freshness (ADR 0098 §3, forward) ---------------------


def test_stubbed_recipe_reddens(tmp_path, capsys) -> None:
    """A recipe whose body is `true` produces nothing, so its document is unclaimed."""
    assert _run(_tree(tmp_path, justfile="demo-docs:\n    true\n")) == 1
    err = capsys.readouterr().err
    assert "docs/generated/page.md" in err
    assert "did not produce it" in err


def test_stale_committed_document_reddens(tmp_path, capsys) -> None:
    """A hand edit to a generated page is a difference, and the diff is shown."""
    root = _tree(tmp_path, committed={"page.md": _page("# edited by hand")})

    assert _run(root) == 1
    err = capsys.readouterr().err
    assert "stale: docs/generated/page.md" in err
    assert "-# edited by hand" in err
    assert "+# demo" in err


def test_only_the_first_few_differences_carry_a_diff(tmp_path, capsys) -> None:
    """A format change makes every page differ at once; the report stays readable."""
    root = _tree(
        tmp_path,
        produced={f"page{index}.md": _page(f"# generated {index}") for index in range(6)},
        committed={f"page{index}.md": _page(f"# committed {index}") for index in range(6)},
    )

    assert _run(root) == 1
    err = capsys.readouterr().err
    assert err.count("stale: docs/generated/page") == 6
    assert err.count("--- docs/generated/page") == check_generated_docs._MAX_DIFFS


def test_generated_output_that_is_not_committed_reddens(tmp_path, capsys) -> None:
    """The registry grew a page and nobody regenerated: the new page is missing."""
    root = _tree(
        tmp_path,
        produced={"page.md": _page("# demo"), "extra.md": _page("# extra")},
    )

    assert _run(root) == 1
    assert (
        "docs/generated/extra.md: produced by `just demo-docs` but not tracked by git"
        in capsys.readouterr().err
    )


def test_generated_output_left_untracked_reddens(tmp_path, capsys) -> None:
    """The page was regenerated and never staged: green here, red on a fresh clone.

    The walk is `git ls-files`, so a page sitting in the directory but absent from
    the repository is reported rather than making the local run agree with itself.
    """
    root = _tree(
        tmp_path,
        produced={"page.md": _page("# demo"), "extra.md": _page("# extra")},
    )
    _stage(root)
    (root / "docs" / "generated" / "extra.md").write_text(
        _page("# extra"), encoding="utf-8"
    )

    assert check_generated_docs.main(["--repo-root", str(root)]) == 1
    assert (
        "docs/generated/extra.md: produced by `just demo-docs` but not tracked by git"
        in capsys.readouterr().err
    )


def test_a_tracked_page_deleted_from_the_working_tree_reddens(tmp_path, capsys) -> None:
    """`rm` without `git rm` is its own state, and gets its own message.

    Reporting it as untracked would name the wrong remedy for a file git is still
    carrying.
    """
    pages = {"page.md": _page("# demo"), "extra.md": _page("# extra")}
    root = _tree(tmp_path, produced=pages, committed=pages)
    _stage(root)
    (root / "docs" / "generated" / "extra.md").unlink()

    assert check_generated_docs.main(["--repo-root", str(root)]) == 1
    assert (
        "docs/generated/extra.md: produced by `just demo-docs` and tracked by git, "
        "but missing from the working tree" in capsys.readouterr().err
    )


def test_untracked_documents_are_not_walked(tmp_path) -> None:
    """Vendored and ignored documentation is not the repository's to answer for.

    Reddening `just static` for a file that is not in the repository would be a gate
    with no CI reproduction and no way to silence it.
    """
    root = _tree(tmp_path)
    _stage(root)
    (root / "docs" / "vendored.md").write_text(
        "<!-- Generated by sphinx; DO NOT EDIT -->\n", encoding="utf-8"
    )

    assert check_generated_docs.main(["--repo-root", str(root)]) == 0


def test_output_stamped_with_another_command_reddens(tmp_path, capsys) -> None:
    """A banner has to name the command that produced *this* file, not just any.

    Without the equality, a page could be produced by one command and tell readers
    to run another, and the guard would check it against neither.
    """
    elsewhere = (
        "<!-- Generated by gen.py; do not edit. Regenerate: just elsewhere-docs -->"
    )
    pages = {"page.md": _page("# demo"), "other.md": _page("# other", elsewhere)}
    root = _tree(tmp_path, produced=pages, committed=pages)

    assert _run(root) == 1
    assert (
        "docs/generated/other.md: produced by `just demo-docs` but its first line "
        "does not name that command" in capsys.readouterr().err
    )


def test_generated_output_without_a_banner_reddens(tmp_path, capsys) -> None:
    """A generated page with no banner is a document the walk cannot see."""
    pages = {"page.md": _page("# demo"), "quiet.md": "# no banner\n"}
    root = _tree(tmp_path, produced=pages, committed=pages)

    assert _run(root) == 1
    assert "docs/generated/quiet.md: produced by `just demo-docs` but its first" in (
        capsys.readouterr().err
    )


def test_an_uppercase_suffix_page_is_still_registered(tmp_path) -> None:
    """The walk folds the suffix too, so `PAGE.MD` is a document its banner registers.

    The pair to the test below. Folding in only one of the two places is what left a
    hole; unfold the walk and this tree reports a vacuous arrangement instead.
    """
    pages = {"PAGE.MD": _page("# demo")}

    assert _run(_tree(tmp_path, produced=pages, committed=pages)) == 0


def test_generated_output_without_a_banner_reddens_whatever_the_suffix_case(
    tmp_path, capsys
) -> None:
    """`.MD` is a Markdown page too, and was an unbannered document in silence.

    The walk case-folds, so an uppercase page is registered; the unbannered-output
    clause did not, so the same page skipped the one check that would have named
    it. Folding in one place and not the other is a hole shaped like a fix.
    """
    pages = {"page.md": _page("# demo"), "QUIET.MD": "# no banner\n"}
    root = _tree(tmp_path, produced=pages, committed=pages)

    assert _run(root) == 1
    assert "docs/generated/QUIET.MD: produced by `just demo-docs` but its first" in (
        capsys.readouterr().err
    )


def test_failing_regeneration_command_is_reported(tmp_path, capsys) -> None:
    """A command that exits non-zero is a failure with its status, not a diff."""
    assert _run(_tree(tmp_path, justfile="demo-docs:\n    exit 3\n")) == 1
    err = capsys.readouterr().err
    assert "`just demo-docs` failed with exit status 3" in err
    # The failure is reported as itself, not as 35 mystifying "did not produce" lines.
    assert "did not produce it" not in err


def test_a_broken_generator_does_not_hide_other_differences(tmp_path, capsys) -> None:
    """One command that cannot run is its own finding, not the end of the run."""
    root = _tree(
        tmp_path,
        committed={"page.md": _page("# edited by hand")},
        justfile=JUSTFILE + "\nbroken-docs:\n    exit 3\n",
    )
    (root / "docs" / "other.md").write_text(
        _page(
            "# other",
            "<!-- Generated by other.py; do not edit. Regenerate: just broken-docs -->",
        ),
        encoding="utf-8",
    )

    assert _run(root) == 1
    err = capsys.readouterr().err
    assert "`just broken-docs` failed with exit status 3" in err
    # The surviving command's difference is still reported.
    assert "stale: docs/generated/page.md" in err


def test_hung_regeneration_command_is_killed_with_its_children(
    tmp_path, capsys, monkeypatch
) -> None:
    """A generator that never returns is killed promptly, descendants included.

    Two properties, because the message alone proves neither. The marker is the
    leak: the backgrounded subshell writes it three seconds in, so it appears
    unless the whole process group died at one second -- which is what
    `subprocess.run`'s own timeout handling does *not* do, and what `process.kill()`
    on its own does not do either. The wall clock is the ceiling: with nothing
    killed at all, `Popen.__exit__` waits on a live child for the command's full
    sixty seconds.
    """
    monkeypatch.setattr(check_generated_docs, "_TIMEOUT_SECONDS", 1)
    marker = tmp_path / "descendant-survived"
    monkeypatch.setenv("DOC_FRESHNESS_MARKER", str(marker))
    root = _tree(
        tmp_path,
        justfile=(
            'demo-docs:\n    (sleep 3; touch "$DOC_FRESHNESS_MARKER") &\n    sleep 60\n'
        ),
    )

    started = time.monotonic()
    assert _run(root) == 1
    assert time.monotonic() - started < 15
    assert "`just demo-docs` did not finish within 1s" in capsys.readouterr().err
    time.sleep(5)
    assert not marker.exists(), "a descendant of the timed-out command outlived it"



def test_a_refused_group_kill_still_bounds_the_timeout(
    tmp_path, capsys, monkeypatch
) -> None:
    """`killpg` can be refused, and then nothing has killed the direct child.

    `Popen.__exit__` waits on that child without a bound, so the timeout would stop
    being a ceiling and the guard would sit out the command's full thirty seconds.
    The direct-child kill is the fallback that keeps the promise.
    """

    def refused(*_args: object, **_kwargs: object) -> None:
        raise PermissionError("operation not permitted")

    monkeypatch.setattr(check_generated_docs, "_TIMEOUT_SECONDS", 1)
    monkeypatch.setattr(check_generated_docs.os, "killpg", refused)
    root = _tree(tmp_path, justfile="demo-docs:\n    sleep 30\n")

    started = time.monotonic()
    assert _run(root) == 1
    assert time.monotonic() - started < 10
    assert "`just demo-docs` did not finish within 1s" in capsys.readouterr().err


def test_a_descendant_outside_the_process_group_does_not_extend_the_timeout(
    tmp_path, capsys, monkeypatch
) -> None:
    """`setsid` puts a descendant beyond `killpg`, and it keeps the pipe open.

    Reading that pipe out after the kill waits for a process the guard cannot kill,
    to collect output this path throws away -- measured at the full drain budget
    before the drain was removed. The timeout is a ceiling, so nothing waits.
    """
    if shutil.which("setsid") is None:  # pragma: no cover - present on Linux
        pytest.skip("setsid is needed to put a descendant outside the process group")
    monkeypatch.setattr(check_generated_docs, "_TIMEOUT_SECONDS", 1)
    root = _tree(tmp_path, justfile="demo-docs:\n    setsid sleep 30 &\n    sleep 30\n")

    started = time.monotonic()
    assert _run(root) == 1
    assert time.monotonic() - started < 10
    assert "`just demo-docs` did not finish within 1s" in capsys.readouterr().err

# --- negative controls: the arrangement (ADR 0098 §3, reverse) ---------------


def test_dangling_banner_reddens(tmp_path, capsys) -> None:
    """Delete the recipe and the banner that names it dangles."""
    root = _tree(tmp_path, justfile="other:\n    true\n")

    assert _run(root) == 1
    assert (
        "docs/generated/page.md: names `just demo-docs`, but the justfile defines "
        "no such recipe" in capsys.readouterr().err
    )


def test_orphaned_regeneration_recipe_reddens(tmp_path, capsys) -> None:
    """A `*-docs` recipe no banner names generates nothing that is checked."""
    root = _tree(tmp_path, justfile=JUSTFILE + "\nextra-docs:\n    true\n")

    assert _run(root) == 1
    err = capsys.readouterr().err
    assert f"'extra-docs' regenerates documentation, but {ORPHANED}" in err
    # The recipe that *is* named is not reported as orphaned.
    assert "'demo-docs' regenerates" not in err


def test_deleting_the_only_generated_document_reddens(tmp_path, capsys) -> None:
    """Both reverse clauses fire: the walk is empty and the recipe is orphaned."""
    root = _tree(tmp_path)
    (root / "docs" / "generated" / "page.md").unlink()

    assert _run(root) == 1
    err = capsys.readouterr().err
    assert NO_DOCUMENT in err
    assert f"'demo-docs' regenerates documentation, but {ORPHANED}" in err


def test_a_documentation_tree_with_no_banner_at_all_reddens(tmp_path, capsys) -> None:
    """Non-vacuity standing alone, with no `*-docs` recipe left to orphan.

    This is the clause the rejected design lacked: a universal claim over an empty
    set is true, so the empty set has to be the failure.
    """
    root = _tree(tmp_path, committed={}, justfile="other:\n    true\n")
    (root / "docs" / "handbook.md").write_text("# hand written\n", encoding="utf-8")

    assert _run(root) == 1
    err = capsys.readouterr().err
    assert NO_DOCUMENT in err
    assert "regenerates documentation" not in err


# --- banner grammar ----------------------------------------------------------


def test_malformed_banner_reddens(tmp_path, capsys) -> None:
    """A near-miss banner fails rather than dropping out of the walked set."""
    broken = "<!-- Generated by gen.py; do not edit -->"
    root = _tree(
        tmp_path,
        produced={"page.md": _page("# demo", broken)},
        committed={"page.md": _page("# demo", broken)},
    )

    assert _run(root) == 1
    assert (
        "docs/generated/page.md: first line looks like a generation banner"
        in capsys.readouterr().err
    )


def test_banner_naming_a_recipe_outside_the_convention_reddens(
    tmp_path, capsys, monkeypatch
) -> None:
    """The guard runs what the banner names, so the banner may not name `setup`.

    The side effect is checked first and lands on an absolute path. Inside the
    scratch tree it could not be observed at all, and asserting on the message
    first would let the message change mask a banner that actually ran `setup`.
    """
    banner = "<!-- Generated by gen.py; do not edit. Regenerate: just setup -->"
    ran = tmp_path / "setup-ran"
    monkeypatch.setenv("DOC_FRESHNESS_MARKER", str(ran))
    root = _tree(
        tmp_path,
        produced={"page.md": _page("# demo", banner)},
        committed={"page.md": _page("# demo", banner)},
        justfile=JUSTFILE + '\nsetup:\n    touch "$DOC_FRESHNESS_MARKER"\n',
    )

    assert _run(root) == 1
    assert not ran.exists(), "a banner chose what to run against the real environment"
    assert (
        "docs/generated/page.md: first line looks like a generation banner"
        in capsys.readouterr().err
    )


def test_prose_that_merely_mentions_generation_is_not_a_near_miss(tmp_path) -> None:
    """The near-miss clause is anchored on the comment opener, not on the phrase.

    A page titled after a generated artefact is ordinary prose. Failing it would
    make the gate unfixable except by retitling someone's document.
    """
    root = _tree(tmp_path)
    (root / "docs" / "exports.md").write_text(
        "# Reports generated by the nightly export\n\nDo not edit these by hand.\n",
        encoding="utf-8",
    )

    assert _run(root) == 0


def test_prose_quoting_a_banner_is_not_treated_as_generated(tmp_path) -> None:
    """A record explaining the banner format carries it below its own first line.

    ADR 0098 quotes the exact banner inside a fenced block. Reading only the first
    line is what keeps that record out of the walk.
    """
    root = _tree(tmp_path)
    (root / "docs" / "note.md").write_text(
        f"# About banners\n\n```\n{BANNER}\n```\n", encoding="utf-8"
    )

    assert _run(root) == 0


def test_a_banner_outside_the_docs_tree_reddens(tmp_path, capsys) -> None:
    """The walk covers docs/; a banner anywhere else is a document nothing checks."""
    root = _tree(tmp_path)
    (root / "REFERENCE.md").write_text(_page("# stale mirror"), encoding="utf-8")

    assert _run(root) == 1
    assert "REFERENCE.md: carries a generation banner but lives outside docs/" in (
        capsys.readouterr().err
    )


# --- operating conditions ----------------------------------------------------


def test_missing_docs_directory_fails(tmp_path, capsys) -> None:
    """A moved documentation tree fails rather than passing over nothing."""
    root = _tree(tmp_path)
    shutil.rmtree(root / "docs")

    assert _run(root) == 1
    assert "documentation directory not found" in capsys.readouterr().err


def test_missing_justfile_fails(tmp_path, capsys) -> None:
    """Without the justfile neither direction of the check can be derived."""
    root = _tree(tmp_path)
    (root / "justfile").unlink()

    assert _run(root) == 1
    assert "justfile not found" in capsys.readouterr().err


def test_a_repository_tracking_nothing_fails(tmp_path, capsys) -> None:
    """A tree with nothing staged is not the repository the guard checks.

    Reported as itself rather than as an empty walk, which would name the wrong
    remedy: the fix is `git add`, not writing a generated document.
    """
    root = _tree(tmp_path)

    assert check_generated_docs.main(["--repo-root", str(root)]) == 1
    assert "tracks no files" in capsys.readouterr().err


def test_unreadable_justfile_fails(tmp_path, capsys) -> None:
    """A justfile `just` cannot parse is reported as that, not as an empty recipe set."""
    root = _tree(tmp_path, justfile="this line is not a recipe\n")

    assert _run(root) == 1
    assert "`just --summary` failed" in capsys.readouterr().err
